//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeTime1.Models
{
    using System;
    using System.Collections.Generic;

    public partial class DonHangDat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonHangDat()
        {
            this.HangDonHangDats = new HashSet<HangDonHangDat>();
        }

        public string MaDHD { get; set; }
        public string MaKH { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public string TrangThai { get; set; }
        public Nullable<System.DateTime> NgayGiao { get; set; }
        public Nullable<System.DateTime> NgayHoanThanh { get; set; }
        public System.DateTime NgayBatDau { get; set; }
        public bool DaXoa { get; set; }
        public decimal TongDonHang { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HangDonHangDat> HangDonHangDats { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
