//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeTime1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Hang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hang()
        {
            this.HangDonHangNhaps = new HashSet<HangDonHangNhap>();
            this.HangDonHangXuats = new HashSet<HangDonHangXuat>();
        }
        [Key]
        [Display(Name = "Mã hàng")]
        public string MaH { get; set; }
        [Display(Name = "Mã mặt hàng")]
        public string MaMH { get; set; }
        [Display(Name = "Mã nhà cung cấp")]
        public string MaNCC { get; set; }
        [Display(Name = "Hạn sử dụng")]
        public DateTime? HanSuDung { get; set; }
        [Display(Name = "Ngày nhập")]
        public System.DateTime NgayNhap { get; set; }
        [Display(Name = "Giá nhập")]
        public decimal GiaNhap { get; set; }
        [Display(Name = "Số lượng")]
        public int SoLuong { get; set; }
        [Display(Name = "Giá bán")]
        public decimal GiaBan { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HangDonHangNhap> HangDonHangNhaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HangDonHangXuat> HangDonHangXuats { get; set; }
        public virtual MauHang MauHang { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
    }
}
