//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeTime1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class HangDonHangNhap
    {
        [Required]
        public string MaDHN { get; set; }
        [Required]
        public string MaH { get; set; }
        [Required]
        public int SoLuong { get; set; }
        [Required]

        public virtual DonHangNhap DonHangNhap { get; set; }
        [Required]
        public virtual Hang Hang { get; set; }
    }
}
