//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeTime1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;

    public partial class QLTapHoaEntities : DbContext
    {
        public QLTapHoaEntities()
            : base("name=QLTapHoaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DonHangNhap> DonHangNhaps { get; set; }
        public virtual DbSet<DonHangXuat> DonHangXuats { get; set; }
        public virtual DbSet<Hang> Hangs { get; set; }
        public virtual DbSet<HangDonHangNhap> HangDonHangNhaps { get; set; }
        public virtual DbSet<HangDonHangXuat> HangDonHangXuats { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<MauHang> MauHangs { get; set; }
        public virtual DbSet<NguoiDung> NguoiDungs { get; set; }
        public virtual DbSet<NhaCungCap> NhaCungCaps { get; set; }
        public virtual DbSet<NhomHang> NhomHangs { get; set; }

        //public virtual int Hang_TimKiem(string HanSuDung, string NgayNhap, string GiaNhap,
        //    string SoLuong, string GiaBan, string TenMH, string TenNCC)
        //{
        //    var HanSuDungParameter = HanSuDung != null ?
        //        new ObjectParameter("HanSuDung", HanSuDung) :
        //        new ObjectParameter("HanSuDung", typeof(string));

        //    var NgayNhapParameter = NgayNhap != null ?
        //        new ObjectParameter("NgayNhap", NgayNhap) :
        //        new ObjectParameter("NgayNhap", typeof(string));

        //    var GiaNhapParameter = GiaNhap != null ?
        //        new ObjectParameter("GiaNhap", GiaNhap) :
        //        new ObjectParameter("GiaNhap", typeof(string));

        //    var SoLuongParameter = SoLuong != null ?
        //        new ObjectParameter("SoLuong", SoLuong) :
        //        new ObjectParameter("SoLuong", typeof(string));

        //    var GiaBanParameter = GiaBan != null ?
        //        new ObjectParameter("GiaBan", GiaBan) :
        //        new ObjectParameter("GiaBan", typeof(string));

        //    var TenMHParameter = TenMH != null ?
        //        new ObjectParameter("TenMH", TenMH) :
        //        new ObjectParameter("TenMH", typeof(string));

        //    var TenNCCParameter = TenNCC != null ?
        //        new ObjectParameter("TenNCC", TenNCC) :
        //        new ObjectParameter("TenNCC", typeof(string));

        //    return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Hang_TimKiem", HanSuDungParameter, NgayNhapParameter,
        //        GiaNhapParameter, SoLuongParameter, GiaBanParameter, TenMHParameter, TenNCCParameter);
        //}
    }
}
